server:
  address: 0.0.0.0
  port: ${SERVER_PORT}

spring:
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: ${DB_DRIVER}
    # 읽기 전용 설정
    hikari:
      maximum-pool-size: 5
      minimum-idle: 1
      connection-timeout: 30000
      read-only: true

  jpa:
    hibernate:
      ddl-auto: validate  # 스키마 검증만
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        # 읽기 전용 설정
        connection.provider_disables_autocommit: true
    show-sql: true
    # 읽기 전용 설정
    open-in-view: false

# 로깅 설정 - 간단하게
logging:
  level:
    root: WARN
    shop.jazzmate.jazzmateshop: INFO
